# trigger-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trigger-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: default
roleRef:
  kind: ClusterRole
  name: trigger-clusterrole
  apiGroup: rbac.authorization.k8s.io
